version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 7.0
    commands:
      - echo Installing dependencies...
      - dotnet restore

  pre_build:
    commands:
      - echo Building the project...
      - dotnet build

  build:
    commands:
      - echo Testing the project...
      - dotnet test

  post_build:
    commands:
      - echo Build completed!

artifacts:
  files:
    - '**/*'
  discard-paths: yes
